version: '3.7'

services:

  gif-expert-app:
    container_name: gif-expert-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
